### ISSUE TITLE
The api-client-python is not compatible with python 3.7

### ISSUE THREAD

**Issue by amierzwicki** [launchdarkly/api-client-python#1]
Looks like code uses "async" as parameter name which is now a reserved keyword in python 3.7. Would be great if the code were adjusted so we can run it under python 3.7.

Not sure if this is the only blocker from using new python.

**Comment by InTheCloudDan** [comment]
@amierzwicki this should be fixed now, the `async` should now be `async_req`. Can you confirm this is working for you?

**Comment by bwoskow-ld** [comment]
@amierzwicki we're going to close this issue. Let us know if you still continue running into any issues with Python 3.7.
