### ISSUE TITLE
Updates to Copy Feature Flag across Environments

### ISSUE THREAD

**Issue by Boylancl** [launchdarkly/api-client-python#2]
Following the example on https://github.com/launchdarkly/api-client-python/blob/master/docs/FeatureFlagsApi.md#copy_feature_flag
Throws 404's constantly and the API endpoint `POST /flags/{projectKey}/{environmentKey}/{featureFlagKey}/copy` doesn't appear to match the API documentation on the website https://apidocs.launchdarkly.com/reference#copy-feature-flag which is calls out `POST /flags/projKey/flagKey/copy`

**Comment by InTheCloudDan** [comment]
Hi @Boylancl sorry for the delay on this. Can you please try out the latest version? Copy flags should be working now.

**Comment by Boylancl** [comment]
Thanks - We worked around this by iterating the list of flags and copying them over individually. I'll remember this fix if we get a chance to revisit the code.
