### ISSUE TITLE
How do I get the client side MAU?

### ISSUE THREAD

**Issue by Michael-Dougherty** [launchdarkly/api-client-python#6]
Hello, I am trying to get the Client Side MAU for the projects and I am able to get the server side using get mau usage rest end point. (https://apidocs.launchdarkly.com/reference#usage-mau) How do I get the client side MAU?

**Comment by annabkr** [comment]
Hi @Michael-Dougherty, you can get the Client-Side MAU by making a request to the [Get MAU Usage endpoint](https://apidocs.launchdarkly.com/reference#usage-mau) with the query parameter `sdktype` set to `client`:

 ```
GET https://app.launchdarkly.com/api/v2/usage/mau?sdktype=client
```

Here is the [link to the method](https://github.com/launchdarkly/api-client-python/blob/d51323be2d3125b68eaa67f5b48c1ce9ecb6c192/launchdarkly_api/api/customer_metrics_api.py#L327)  for that endpoint.

Thank you for bringing this to our attention. It looks like the API documentation had not been updated to reflect that optional parameter. I've filed a ticket to get the documentation up to date.

Hope that helps.

**Comment by Michael-Dougherty** [comment]
It does thank you.
Mike

**Comment by Michael-Dougherty** [comment]
Thank you this does help. One other question if I may, how to I get the client MAUs for the projects? Like the one on breakdown view?
https://app.launchdarkly.com/settings/usage/details/client

**Comment by annabkr** [comment]
> One other question if I may, how do I get the client MAUs for the projects? Like the one on breakdown view?
> https://app.launchdarkly.com/settings/usage/details/client

That view is powered by the [same API](https://apidocs.launchdarkly.com/reference#usage-mau), with another query parameter that it appears is also not documented. Thank you for raising this! 

If you append a `groupby` query parameter set to `project`, that will hopefully give you what you're looking for:

```
GET https://app.launchdarkly.com/api/v2/usage/mau?sdktype=client&groupby=project
``` 
 
 Let me know if that helps.

**Comment by Michael-Dougherty** [comment]
You are the best! thank you again.
